export const AUTH_MODAL_OPEN = 'AUTH_MODAL_OPEN'
export const AUTH_MODAL_CLOSE = 'AUTH_MODAL_CLOSE'
export const AUTH_MODAL_SIGNUP = 'AUTH_MODAL_SIGNUP'
export const AUTH_MODAL_LOGIN = 'AUTH_MODAL_LOGIN'
