export const FOLLOW_A_USER = 'FOLLOW_A_USER'
export const UNFOLLOW_A_USER = 'UNFOLLOW_A_USER'

export const FETCH_FOLLOWING = 'FETCH_FOLLOWING'
export const FETCH_SUGGESTED = 'FETCH_SUGGESTED'
export const FETCH_FOLLOWERS = 'FETCH_FOLLOWERS'
export const FETCH_POSTS_COUNT = 'FETCH_POSTS_COUNT'
