export const FETCH_AUTH = 'FETCH_AUTH'

export const AUTH_MODAL_TOGGLE = 'AUTH_MODAL_TOGGLE'
export const AUTH_MODAL_SIGNUP = 'AUTH_MODAL_SIGNUP'
export const AUTH_MODAL_LOGIN = 'AUTH_MODAL_LOGIN'

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const RESET_SEARCH_TERM = 'RESET_SEARCH_TERM'

export const FETCH_USER = 'FETCH_USER'
export const EDIT_USER = 'EDIT_USER'

export const FOLLOW_A_USER = 'FOLLOW_A_USER'
export const UNFOLLOW_A_USER = 'UNFOLLOW_A_USER'

export const FETCH_FOLLOWING = 'FETCH_FOLLOWING'
export const FETCH_SUGGESTED = 'FETCH_SUGGESTED'
export const FETCH_FOLLOWERS = 'FETCH_FOLLOWERS'

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS'
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS'

export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS'
export const CREATE_COLLECTION = 'CREATE_COLLECTION'
export const EDIT_COLLECTION = 'EDIT_COLLECTION'
export const DELETE_COLLECTION = 'DELETE_COLLECTION'

export const ADD_TO_FEED = 'ADD_TO_FEED'
