export const FETCH_AUTH = 'FETCH_AUTH'

export const FETCH_USER = 'FETCH_USER'
export const EDIT_USER = 'EDIT_USER'

export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS'
export const CREATE_COLLECTION = 'CREATE_COLLECTION'
export const EDIT_COLLECTION = 'EDIT_COLLECTION'
export const DELETE_COLLECTION = 'DELETE_COLLECTION'

export const ADD_TO_FEED = 'ADD_TO_FEED'
