export const FETCH_PROFILE_COLLECTION = 'FETCH_PROFILE_COLLECTION'
export const FETCH_PROFILE_FOLLOWING = 'FETCH_PROFILE_FOLLOWING'
export const FETCH_PROFILE_FOLLOWERS = 'FETCH_PROFILE_FOLLOWERS'
export const FETCH_PROFILE_DETAILS = 'FETCH_PROFILE_DETAILS'
