export const FETCH_FEED = 'FETCH_FEED'
export const INCREMENT_OFFSET = 'INCREMENT_OFFSET'
export const TOGGLE_HAS_MORE = 'TOGGLE_HAS_MORE'
export const FETCH_MORE_FEED = 'FETCH_MORE_FEED'
export const FETCH_LOCKER = 'FETCH_LOCKER'

export const FETCH_TOP_TAGS = 'FETCH_TOP_TAGS'
