export const FETCH_FEED = 'FETCH_FEED'
export const INCREMENT_OFFSET = 'INCREMENT_OFFSET'
export const TOGGLE_HAS_MORE = 'TOGGLE_HAS_MORE'

export const FETCH_LOCKER = 'FETCH_LOCKER'

export const CREATE_COMMENT = 'CREATE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const LIKE_COMMENT = 'LIKE_COMMENT'
export const UNLIKE_COMMENT = 'UNLIKE_COMMENT'
