export const FETCH_AUTH = 'FETCH_AUTH'
export const FETCH_USER = 'FETCH_USER'

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS'

export const CREATE_COMMENT = 'CREATE_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const LIKE_COMMENT = 'LIKE_COMMENT'
export const UNLIKE_COMMENT = 'UNLIKE_COMMENT'

export const PONY_UP = 'PONY_UP'
export const PONY_DOWN = 'PONY_DOWN'

export const UPDATE_HEADER_PICTURE = 'UPDATE_HEADER_PICTURE'
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE'
